/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package equacao;

/**
 *
 * @author Marco Tulio
 */
public class EquacaoClass extends javax.swing.JFrame {

    /**
     * Creates new form EquacaoClass
     */
    public EquacaoClass() {
        initComponents();
        painelRes.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aSpinner = new javax.swing.JSpinner();
        bSpinner = new javax.swing.JSpinner();
        cSpinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        eqBase1 = new javax.swing.JLabel();
        eqBase8 = new javax.swing.JLabel();
        eqBase6 = new javax.swing.JLabel();
        cLbl = new javax.swing.JLabel();
        eqBase2 = new javax.swing.JLabel();
        bLbl = new javax.swing.JLabel();
        eqBase4 = new javax.swing.JLabel();
        bLbl2 = new javax.swing.JLabel();
        eqBase3 = new javax.swing.JLabel();
        aLbl = new javax.swing.JLabel();
        eqBase5 = new javax.swing.JLabel();
        aLbl2 = new javax.swing.JLabel();
        cLbl2 = new javax.swing.JLabel();
        btt = new javax.swing.JButton();
        painelRes = new javax.swing.JPanel();
        eqBase9 = new javax.swing.JLabel();
        eqBase7 = new javax.swing.JLabel();
        resultDelta = new javax.swing.JLabel();
        raizReal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        aSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        aSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                aSpinnerStateChanged(evt);
            }
        });

        bSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                bSpinnerStateChanged(evt);
            }
        });

        cSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cSpinnerStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("a");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("b");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("c");

        eqBase1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        eqBase1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eqBase1.setText("x²+");

        eqBase8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        eqBase8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eqBase8.setText(".");

        eqBase6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        eqBase6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eqBase6.setText(".");

        cLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cLbl.setForeground(new java.awt.Color(255, 51, 0));
        cLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cLbl.setText("c");

        eqBase2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        eqBase2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eqBase2.setText("x+");

        bLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bLbl.setForeground(new java.awt.Color(255, 0, 0));
        bLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bLbl.setText("b");

        eqBase4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        eqBase4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eqBase4.setText("Δ =");

        bLbl2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bLbl2.setForeground(new java.awt.Color(255, 0, 0));
        bLbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bLbl2.setText("b");

        eqBase3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        eqBase3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eqBase3.setText("= 0");

        aLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        aLbl.setForeground(new java.awt.Color(255, 0, 0));
        aLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aLbl.setText("a");

        eqBase5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        eqBase5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eqBase5.setText("² - 4");

        aLbl2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        aLbl2.setForeground(new java.awt.Color(255, 0, 0));
        aLbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aLbl2.setText("a");

        cLbl2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cLbl2.setForeground(new java.awt.Color(255, 51, 0));
        cLbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cLbl2.setText("c");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(aLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eqBase1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eqBase2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cLbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(eqBase4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bLbl2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eqBase5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eqBase8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aLbl2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(eqBase6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cLbl2))
                    .addComponent(eqBase3))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aLbl)
                    .addComponent(eqBase1)
                    .addComponent(bLbl)
                    .addComponent(eqBase2)
                    .addComponent(cLbl)
                    .addComponent(eqBase3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bLbl2)
                    .addComponent(eqBase4)
                    .addComponent(aLbl2)
                    .addComponent(cLbl2)
                    .addComponent(eqBase5)
                    .addComponent(eqBase6)
                    .addComponent(eqBase8))
                .addContainerGap())
        );

        btt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btt.setText("Calcular Delta");
        btt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttActionPerformed(evt);
            }
        });

        eqBase9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        eqBase9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        eqBase9.setText("Raizes Reais =");

        eqBase7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        eqBase7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        eqBase7.setText("Δ =");

        resultDelta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        resultDelta.setText("0");

        raizReal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        raizReal.setText("0");

        javax.swing.GroupLayout painelResLayout = new javax.swing.GroupLayout(painelRes);
        painelRes.setLayout(painelResLayout);
        painelResLayout.setHorizontalGroup(
            painelResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelResLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelResLayout.createSequentialGroup()
                        .addComponent(eqBase9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(raizReal, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelResLayout.createSequentialGroup()
                        .addComponent(eqBase7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resultDelta, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        painelResLayout.setVerticalGroup(
            painelResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelResLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eqBase7)
                    .addComponent(resultDelta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eqBase9)
                    .addComponent(raizReal))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(aSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(33, 33, 33)
                                        .addComponent(btt))
                                    .addComponent(cSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(painelRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btt)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_aSpinnerStateChanged
        // TODO add your handling code here:
        aLbl.setText(aSpinner.getValue().toString());
        aLbl2.setText(aSpinner.getValue().toString());
    }//GEN-LAST:event_aSpinnerStateChanged

    private void bSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_bSpinnerStateChanged
        // TODO add your handling code here:
        bLbl.setText(bSpinner.getValue().toString());
        bLbl2.setText(bSpinner.getValue().toString());
    }//GEN-LAST:event_bSpinnerStateChanged

    private void cSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cSpinnerStateChanged
        // TODO add your handling code here:
        cLbl.setText(cSpinner.getValue().toString());
        cLbl2.setText(cSpinner.getValue().toString());
    }//GEN-LAST:event_cSpinnerStateChanged

    private void bttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttActionPerformed
        // TODO add your handling code here:
        int a = Integer.parseInt(aSpinner.getValue().toString());
        int b = Integer.parseInt(bSpinner.getValue().toString());
        int c = Integer.parseInt(cSpinner.getValue().toString());
        double somaDelta = Math.round((Math.pow(b, 2)) - (4*a*c));
        
        if (somaDelta >= 0) {
            raizReal.setText("Sim");
        } else {
            raizReal.setText("Não");
        }
        resultDelta.setText(String.format("%.0f", somaDelta));
        if (painelRes.isVisible() == false) {
            painelRes.setVisible(true);
        }
    }//GEN-LAST:event_bttActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EquacaoClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EquacaoClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EquacaoClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EquacaoClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EquacaoClass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aLbl;
    private javax.swing.JLabel aLbl2;
    private javax.swing.JSpinner aSpinner;
    private javax.swing.JLabel bLbl;
    private javax.swing.JLabel bLbl2;
    private javax.swing.JSpinner bSpinner;
    private javax.swing.JButton btt;
    private javax.swing.JLabel cLbl;
    private javax.swing.JLabel cLbl2;
    private javax.swing.JSpinner cSpinner;
    private javax.swing.JLabel eqBase1;
    private javax.swing.JLabel eqBase2;
    private javax.swing.JLabel eqBase3;
    private javax.swing.JLabel eqBase4;
    private javax.swing.JLabel eqBase5;
    private javax.swing.JLabel eqBase6;
    private javax.swing.JLabel eqBase7;
    private javax.swing.JLabel eqBase8;
    private javax.swing.JLabel eqBase9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel painelRes;
    private javax.swing.JLabel raizReal;
    private javax.swing.JLabel resultDelta;
    // End of variables declaration//GEN-END:variables
}
